name: okay_life_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  dio: ^5.7.0 # kakao_flutter_sdk와 호환되는 버전
  kakao_flutter_sdk: ^1.9.6 # 충돌 없는 안정 버전
  sign_in_with_apple: ^6.1.3
  webview_flutter: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.6
  intl: ^0.19.0
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/planet.json
    - assets/planet_bg.png
    - assets/login_bg.png
    - assets/Apple.svg
    - assets/Google.svg
    - assets/Kakao.svg
    - assets/onboarding_icon_1.json
    - assets/onboarding_icon_2.json
    - assets/onboarding_icon_3.json
    - assets/onboarding_bg_1.png
    - assets/rocket.png
    - assets/mascot.svg
    - assets/dashboard_bg.png
    - assets/sun-star.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
